apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["Namespace"]
    resourceNames: ["argocd"]
    verbs: ["get","list","watch"]

      
    