name: Terratest

on:
  workflow_dispatch:
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read   

jobs:
  terrratest:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform configuration
        working-directory: terraform
        run: terraform validate
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Run Terratest
        run: |
          cd terraform/terratest
          go mod tidy
          go test -timeout 120m